name: deep_blue
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0" # or sdk: ^3.5.4 if you prefer

dependencies:
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.0+2
  flutter_speed_dial: ^7.0.0
  carousel_slider: ^5.0.0
  flutter_map: ^7.0.2 # if you want to keep this dependency
  geolocator: ^13.0.2 # if you want to keep this dependency
  latlong2: ^0.9.1 # if you want to keep this dependency
  intl: ^0.20.1 # or ^0.18.0 based on your preference
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^5.0.2
  http: ^1.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
